package enums

// NotificationArea is the area/module a notification belongs to (PascalCase in API).
type NotificationArea string

const (
	NotificationAreaUnknown        NotificationArea = "Unknown"
	NotificationAreaMessages       NotificationArea = "Messages"
	NotificationAreaCalendar       NotificationArea = "Calendar"
	NotificationAreaPosts          NotificationArea = "Posts"
	NotificationAreaSchedule       NotificationArea = "Schedule"
	NotificationAreaAdministration NotificationArea = "Administration"
	NotificationAreaGallery        NotificationArea = "Gallery"
	NotificationAreaDocuments      NotificationArea = "Documents"
	NotificationAreaAlbum          NotificationArea = "Album"
	NotificationAreaPresence       NotificationArea = "Presence"
	NotificationAreaWidget         NotificationArea = "Widget"
	NotificationAreaFileScanning   NotificationArea = "FileScanning"
)

// NotificationEventType is the specific notification event type (PascalCase in API).
type NotificationEventType string

const (
	NotificationEventTypeOther                                 NotificationEventType = "Other"
	NotificationEventTypeNewMessagePrivateInbox                NotificationEventType = "NewMessagePrivateInbox"
	NotificationEventTypeNewSensitiveMessagePrivateInbox       NotificationEventType = "NewSensitiveMessagePrivateInbox"
	NotificationEventTypeInvitedToEventNoResponseRequired      NotificationEventType = "InvitedToEventNoResponseRequired"
	NotificationEventTypeInvitedToEventResponseRequired        NotificationEventType = "InvitedToEventResponseRequired"
	NotificationEventTypeEventChangedResponseRequired          NotificationEventType = "EventChangedResponseRequired"
	NotificationEventTypeEventChangedNoResponseRequired        NotificationEventType = "EventChangedNoResponseRequired"
	NotificationEventTypeEventCancelledNoReason                NotificationEventType = "EventCancelledNoReason"
	NotificationEventTypeInvitedToParentalMeeting              NotificationEventType = "InvitedToParentalMeeting"
	NotificationEventTypeInvitedToSchoolHomeMeeting            NotificationEventType = "InvitedToSchoolHomeMeeting"
	NotificationEventTypeInvitedToPerformanceMeeting           NotificationEventType = "InvitedToPerformanceMeeting"
	NotificationEventTypeGrantedRightsForOtherCalendar         NotificationEventType = "GrantedRightsForOtherCalendar"
	NotificationEventTypeRemovedRightsForOthersCalendar        NotificationEventType = "RemovedRightsForOthersCalendar"
	NotificationEventTypeLostRoomExternalScheduling            NotificationEventType = "LostRoomBecauseOfExternalScheduling"
	NotificationEventTypeSomeoneRemovedYourResponse            NotificationEventType = "SomeoneElseRemovedYourResponseToEvent"
	NotificationEventTypeSomeoneRespondedToEvent               NotificationEventType = "SomeoneElseRespondedToEvent"
	NotificationEventTypePostSharedWithMe                      NotificationEventType = "PostSharedWithMe"
	NotificationEventTypePostRemovedFromGroupByAdmin           NotificationEventType = "PostWasRemovedFromGroupByAdmin"
	NotificationEventTypePostWasDeleted                        NotificationEventType = "PostWasDeleted"
	NotificationEventTypeSubstituteAdded                       NotificationEventType = "SubstituteAdded"
	NotificationEventTypeDashboardWasUpdated                   NotificationEventType = "DashboardWasUpdated"
	NotificationEventTypeNewMedia                              NotificationEventType = "NewMedia"
	NotificationEventTypeTaggedInMedia                         NotificationEventType = "TaggedInMedia"
	NotificationEventTypeTaggedInMediaWithoutPush              NotificationEventType = "TaggedInMediaWithoutPushNotification"
	NotificationEventTypeMediaAddedToAlbum                     NotificationEventType = "MediaAddedToAlbum"
	NotificationEventTypeAlbumShared                           NotificationEventType = "AlbumShared"
	NotificationEventTypeNewOrUpdatedSecureDocument            NotificationEventType = "NewOrUpdatedSecureDocument"
	NotificationEventTypeNewCommonFile                         NotificationEventType = "NewCommonFile"
	NotificationEventTypeVacationResponseRequired              NotificationEventType = "VacationResponseRequired"
	NotificationEventTypeInvitedToRepeatingEvent               NotificationEventType = "InvitedToRepeatingEvent"
	NotificationEventTypePresenceRegUpdatedExitWith            NotificationEventType = "PresenceRegistrationUpdatedExitWith"
	NotificationEventTypeUpdatedSharingCommonFile              NotificationEventType = "UpdatedSharingCommonFile"
	NotificationEventTypeNewOrUpdatedCommonFile                NotificationEventType = "NewOrUpdatedCommonFile"
	NotificationEventTypeVacationRequestCancelledNoReason      NotificationEventType = "VacationRequestCancelledNoReason"
	NotificationEventTypeNewMessageCommonInbox                 NotificationEventType = "NewMessageCommonInbox"
	NotificationEventTypeNewSensitiveMessageCommonInbox        NotificationEventType = "NewSensitiveMessageCommonInbox"
	NotificationEventTypeAddedToCommonInbox                    NotificationEventType = "AddedToCommonInbox"
	NotificationEventTypeRemovedFromCommonInbox                NotificationEventType = "RemovedFromCommonInbox"
	NotificationEventTypeLessonNoteChanged                     NotificationEventType = "LessonNoteChanged"
	NotificationEventTypeEventChangedBySomeoneElse             NotificationEventType = "EventChangedBySomeoneElse"
	NotificationEventTypeEventCancelledBySomeoneElse           NotificationEventType = "EventCancelledBySomeoneElse"
	NotificationEventTypeWidgetNotification                    NotificationEventType = "WidgetNotification"
	NotificationEventTypeInvitedToExceptionEvent               NotificationEventType = "InvitedToExceptionEvent"
	NotificationEventTypeInvitedToSingleOccurrence             NotificationEventType = "InvitedToSingleOccurrenceOfEvent"
	NotificationEventTypeSingleOccurrenceCancelled             NotificationEventType = "SingleOccurrenceEventCancelledNoReason"
	NotificationEventTypeInvitedToSurvey                       NotificationEventType = "InvitedToSurvey"
	NotificationEventTypeDeletionRulesInfo                     NotificationEventType = "DeletionRulesInfo"
	NotificationEventTypeResourceReservationDeclined           NotificationEventType = "ResourceReservationDeclined"
	NotificationEventTypeGeneralInformationSent                NotificationEventType = "GeneralInformationSent"
	NotificationEventTypeNewPostComment                        NotificationEventType = "NewPostComment"
	NotificationEventTypeOSOutdated                            NotificationEventType = "OSOutdated"
	NotificationEventTypeFileScanFailedPost                    NotificationEventType = "FileScanFailedPost"
	NotificationEventTypeFileScanFailedEvent                   NotificationEventType = "FileScanFailedEvent"
	NotificationEventTypeFileScanFailedPrivateInbox            NotificationEventType = "FileScanFailedPrivateInboxMessage"
	NotificationEventTypeFileScanFailedCommonInbox             NotificationEventType = "FileScanFailedCommonInboxMessage"
	NotificationEventTypeFileScanFailedInternalSecure          NotificationEventType = "FileScanFailedInternalSecureDocument"
	NotificationEventTypeFileScanFailedExternalSecure          NotificationEventType = "FileScanFailedExternalSecureFile"
	NotificationEventTypeFileScanFailedAlbum                   NotificationEventType = "FileScanFailedAlbum"
	NotificationEventTypeFileScanFailedProfilePicture          NotificationEventType = "FileScanFailedProfilePicture"
	NotificationEventTypeFileScanFailedCommonFile              NotificationEventType = "FileScanFailedCommonFile"
)

// NotificationEventTypeCategories groups notification event types (camelCase).
type NotificationEventTypeCategories string

const (
	NotificationCategoryAlertInviteWithResponse       NotificationEventTypeCategories = "alertInviteWithResponse"
	NotificationCategoryAlertChangedWithResponse      NotificationEventTypeCategories = "alertChangedWithResponse"
	NotificationCategoryAlertChangedWithoutResponse   NotificationEventTypeCategories = "alertChangedWithoutResponse"
	NotificationCategoryAlertInviteSubstitute         NotificationEventTypeCategories = "alertInviteAssignedAsSubstituteTeacher"
	NotificationCategoryAlertInviteGoToAfterClick     NotificationEventTypeCategories = "alertInviteGoToAfterClickAndShowCross"
	NotificationCategoryAlertInvite                   NotificationEventTypeCategories = "alertInvite"
	NotificationCategoryNotificationWithoutAlert      NotificationEventTypeCategories = "notificationWithoutAlert"
	NotificationCategoryPosts                         NotificationEventTypeCategories = "posts"
	NotificationCategoryMessages                      NotificationEventTypeCategories = "messages"
	NotificationCategorySchedule                      NotificationEventTypeCategories = "schedule"
	NotificationCategoryOther                         NotificationEventTypeCategories = "other"
	NotificationCategoryAlertSurveyInvite             NotificationEventTypeCategories = "alertSurveyInvite"
	NotificationCategoryAlertDeletionRulesInfo        NotificationEventTypeCategories = "alertDeletionRulesInfo"
	NotificationCategoryAlertResourceDeclined         NotificationEventTypeCategories = "alertResourceReservationDeclined"
	NotificationCategoryAlertGeneralInfo              NotificationEventTypeCategories = "alertGeneralInfo"
	NotificationCategoryAlertOSOutdated               NotificationEventTypeCategories = "alertOSOutdated"
	NotificationCategoryFileScanFailed                NotificationEventTypeCategories = "fileScanFailed"
)

// NotificationSettingsEnum represents notification settings sections (camelCase).
type NotificationSettingsEnum string

const (
	NotifSettingsContentSection              NotificationSettingsEnum = "contentSettingsSection"
	NotifSettingsPlatformSection             NotificationSettingsEnum = "platformSettingsSection"
	NotifSettingsMessageSubsection           NotificationSettingsEnum = "messageSubsection"
	NotifSettingsCalendarSubsection          NotificationSettingsEnum = "calendarSubsection"
	NotifSettingsMediaSubsection             NotificationSettingsEnum = "mediaSubsection"
	NotifSettingsPostsSubsection             NotificationSettingsEnum = "postsSubsection"
	NotifSettingsComeGoSubsection            NotificationSettingsEnum = "comeGoSubsection"
	NotifSettingsWidgetsSubsection           NotificationSettingsEnum = "widgetsSubsection"
	NotifSettingsEmployeeAllowed             NotificationSettingsEnum = "employeeAllowed"
	NotifSettingsGuardianAllowed             NotificationSettingsEnum = "guardianAllowed"
	NotifSettingsChildAllowed                NotificationSettingsEnum = "childAllowed"
	NotifSettingsCalendarAllowed             NotificationSettingsEnum = "calendarAllowed"
	NotifSettingsNotifySubstituteAllowed     NotificationSettingsEnum = "notifySubstituteTeacherAllowed"
	NotifSettingsNewMediaAllowed             NotificationSettingsEnum = "newMediaAllowed"
	NotifSettingsNewPostsAllowed             NotificationSettingsEnum = "newPostsAllowed"
	NotifSettingsVacationRegRequestAllow     NotificationSettingsEnum = "vacationRegistrationRequestAllow"
	NotifSettingsPickupActivityAllow         NotificationSettingsEnum = "pickupActivityAllow"
	NotifSettingsNotifyLessonsChangeAllowed  NotificationSettingsEnum = "notifyLessonsChangeAllowed"
	NotifSettingsWidgetsAllowed              NotificationSettingsEnum = "widgetsAllowed"
	NotifSettingsMobileNotAvailableText      NotificationSettingsEnum = "mobileNotAvailableText"
	NotifSettingsMobileNotAvailableInfo      NotificationSettingsEnum = "mobileNotAvailableInfo"
	NotifSettingsMobileSubsection            NotificationSettingsEnum = "mobileSubsection"
	NotifSettingsEmailSubsection             NotificationSettingsEnum = "emailSubsection"
	NotifSettingsConsentSubsection           NotificationSettingsEnum = "consentSubsection"
	NotifSettingsMobileAllowed               NotificationSettingsEnum = "mobileAllowed"
	NotifSettingsEmailAllowed                NotificationSettingsEnum = "emailAllowed"
	NotifSettingsInstant                     NotificationSettingsEnum = "instant"
	NotifSettingsDatePicker                  NotificationSettingsEnum = "datePicker"
	NotifSettingsAllDay                      NotificationSettingsEnum = "allDay"
	NotifSettingsMonday                      NotificationSettingsEnum = "monday"
	NotifSettingsTuesday                     NotificationSettingsEnum = "tuesday"
	NotifSettingsWednesday                   NotificationSettingsEnum = "wednesday"
	NotifSettingsThursday                    NotificationSettingsEnum = "thursday"
	NotifSettingsFriday                      NotificationSettingsEnum = "friday"
	NotifSettingsSaturday                    NotificationSettingsEnum = "saturday"
	NotifSettingsSunday                      NotificationSettingsEnum = "sunday"
	NotifSettingsSetTime                     NotificationSettingsEnum = "setTime"
	NotifSettingsSetDateInWeek               NotificationSettingsEnum = "setDateInWeek"
	NotifSettingsEmailViews                  NotificationSettingsEnum = "emailViews"
)

// NotificationType is the high-level notification classification (PascalCase in API).
type NotificationType string

const (
	NotificationTypeBadge      NotificationType = "Badge"
	NotificationTypeAlert      NotificationType = "Alert"
	NotificationTypeIrrelevant NotificationType = "Irrelevant"
	NotificationTypeUnknown    NotificationType = "Unknown"
)

// RemoteNotificationType is the remote/push notification event type (camelCase).
type RemoteNotificationType string

const (
	RemoteNotifPostSharedWithMe                    RemoteNotificationType = "postSharedWithMe"
	RemoteNotifNewMessagePrivateInbox              RemoteNotificationType = "newMessagePrivateInbox"
	RemoteNotifNewSensitiveMessagePrivateInbox     RemoteNotificationType = "newSensitiveMessagePrivateInbox"
	RemoteNotifInvitedToEventNoResponse            RemoteNotificationType = "invitedToEventNoResponseRequired"
	RemoteNotifInvitedToEventResponseRequired      RemoteNotificationType = "invitedToEventResponseRequired"
	RemoteNotifInvitedToRepeatingEventResponse     RemoteNotificationType = "invitedToRepeatingEventResponseRequired"
	RemoteNotifEventChangedResponseRequired        RemoteNotificationType = "eventChangedResponseRequired"
	RemoteNotifEventChangedNoResponse              RemoteNotificationType = "eventChangedNoResponseRequired"
	RemoteNotifEventCancelledNoReason              RemoteNotificationType = "eventCancelledNoReason"
	RemoteNotifInvitedToParentalMeeting            RemoteNotificationType = "invitedToParentalMeeting"
	RemoteNotifInvitedToSchoolHomeMeeting          RemoteNotificationType = "invitedToSchoolHomeMeeting"
	RemoteNotifInvitedToPerformanceMeeting         RemoteNotificationType = "invitedToPerformanceMeeting"
	RemoteNotifGrantedRightsForOtherCalendar       RemoteNotificationType = "grantedRightsForOtherCalendar"
	RemoteNotifRemovedRightsForOthersCalendar      RemoteNotificationType = "removedRightsForOthersCalendar"
	RemoteNotifLostRoomExternalScheduling          RemoteNotificationType = "lostRoomBecauseOfExternalScheduling"
	RemoteNotifSomeoneRespondedToEvent             RemoteNotificationType = "someoneElseRespondedToEvent"
	RemoteNotifSomeoneRemovedYourResponse          RemoteNotificationType = "someoneElseRemovedYourResponseToEvent"
	RemoteNotifPostRemovedFromGroupByAdmin         RemoteNotificationType = "postWasRemovedFromGroupByAdmin"
	RemoteNotifPostWasDeleted                      RemoteNotificationType = "postWasDeleted"
	RemoteNotifSubstituteAdded                     RemoteNotificationType = "substituteAdded"
	RemoteNotifDashboardWasUpdated                 RemoteNotificationType = "dashboardWasUpdated"
	RemoteNotifAlbumShared                         RemoteNotificationType = "albumShared"
	RemoteNotifMediaAddedToAlbum                   RemoteNotificationType = "mediaAddedToAlbum"
	RemoteNotifTaggedInMedia                       RemoteNotificationType = "taggedInMedia"
	RemoteNotifNewMedia                            RemoteNotificationType = "newMedia"
	RemoteNotifNewCommonFile                       RemoteNotificationType = "newCommonFile"
	RemoteNotifNewOrUpdatedSecureDocument          RemoteNotificationType = "newOrUpdatedSecureDocument"
	RemoteNotifPresenceRegUpdatedExitWith          RemoteNotificationType = "presenceRegistrationUpdatedExitWith"
	RemoteNotifVacationResponseRequired            RemoteNotificationType = "vacationResponseRequired"
	RemoteNotifVacationResponseCancelledNoResponse RemoteNotificationType = "vacationResponseCancelledNoResponse"
	RemoteNotifNewMessageCommonInbox               RemoteNotificationType = "newMessageCommonInbox"
	RemoteNotifNewSensitiveMessageCommonInbox      RemoteNotificationType = "newSensitiveMessageCommonInbox"
	RemoteNotifUnknown                             RemoteNotificationType = "unknown"
	RemoteNotifLessonNoteChanged                   RemoteNotificationType = "lessonNoteChanged"
	RemoteNotifEventChangedBySomeoneElse           RemoteNotificationType = "eventChangedBySomeoneElse"
	RemoteNotifEventCancelledBySomeoneElse         RemoteNotificationType = "eventCancelledBySomeoneElse"
	RemoteNotifWidgetPushNotification              RemoteNotificationType = "widgetPushNotification"
	RemoteNotifInvitedToExceptionEvent             RemoteNotificationType = "invitedToExceptionEvent"
	RemoteNotifInvitedToSingleOccurrence           RemoteNotificationType = "invitedToSingleOccurrenceOfEvent"
	RemoteNotifInvitedToSurvey                     RemoteNotificationType = "invitedToSurvey"
	RemoteNotifGeneralInformation                  RemoteNotificationType = "generalInformation"
	RemoteNotifNewPostComment                      RemoteNotificationType = "newPostComment"
	RemoteNotifFileScanFailedPost                  RemoteNotificationType = "fileScanFailedPost"
	RemoteNotifFileScanFailedEvent                 RemoteNotificationType = "fileScanFailedEvent"
	RemoteNotifFileScanFailedPrivateInbox          RemoteNotificationType = "fileScanFailedPrivateInboxMessage"
	RemoteNotifFileScanFailedCommonInbox           RemoteNotificationType = "fileScanFailedCommonInboxMessage"
	RemoteNotifFileScanFailedInternalSecure        RemoteNotificationType = "fileScanFailedInternalSecureDocument"
	RemoteNotifFileScanFailedExternalSecure        RemoteNotificationType = "fileScanFailedExternalSecureFile"
	RemoteNotifFileScanFailedAlbum                 RemoteNotificationType = "fileScanFailedAlbum"
	RemoteNotifFileScanFailedProfilePicture        RemoteNotificationType = "fileScanFailedProfilePicture"
)
